<a href="https://colab.research.google.com/github/arn97/MLTSA25_ARoy/blob/main/python_bootcamp_MLTSA25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
my_string = "hello"

In [18]:
my_string

'hello'

In [19]:
print(my_string)

hello


In [20]:
my_int = 6

In [21]:
my_float = 6.

In [22]:
print(my_float)

6.0


In [23]:
my_int * my_float

36.0

In [24]:
my_int*my_string

'hellohellohellohellohellohello'

In [25]:
helloworld = "Hello" + " World!"

In [26]:
print(helloworld)

Hello World!


In [27]:
import numpy as np

In [28]:
my_nparr = np.array([1, 2, 3])
my_nparr

array([1, 2, 3])

In [29]:
my_int*my_nparr

array([ 6, 12, 18])

In [30]:
my_bool =True

In [31]:
0 == 1

False

In [32]:
my_int == 1

False

In [33]:
my_int == 6

True

In [34]:
my_int != 6

False

In [36]:
if my_int!=6:
  print("my_int is not equal to 6")
else:
  print("my_int is equal to 6")

print("We're done.")

my_int is equal to 6
We're done.


In [39]:
type(my_int), type(my_float), type(my_string), type(my_nparr), type(my_bool)

(int, float, str, numpy.ndarray, bool)

In [41]:
my_nparr.dtype

dtype('int64')

In [42]:
my_nparr.max()

3

In [43]:
my_nparr.argmax()

2

In [44]:
my_nparr[0]

1

In [45]:
my_nparr[-1]

3

In [46]:
my_nparr[1:]

array([2, 3])

In [47]:
my_nparr[1:2]

array([2])

In [50]:
my_nparr[1:3]

array([2, 3])

In [51]:
list(range(1,4))

[1, 2, 3]

In [54]:
a

0
1
3


In [55]:
np.arange(0,a)

array([0, 1, 2])

In [56]:
def allodds(lastn):
  """
  prints odd numbers
  Input:
      lastn: (int) last number in the list
  Return:
      a list of  odd numbers
  """
  return [i for i in range(1,lastn+1,2)]

def allodds(lastn):
  """
  prints odd numbers
  Input:
      lastn: (int) last number in the list
  Return:
      a list of  odd numbers
  """
  odds = []
  for a in range(1,lastn+1):
    if a%2==1:
      odds.append(a)
  return odds

In [57]:
allodds(10)

[1, 3, 5, 7, 9]

In [79]:
def check_paliondrome(string):
  """
  input:
      str: (string)
  Return:
      True if str is a paliondrome, False otherwise
  """
  if type(string) != str:
    print(f"{string} is not a string")
  elif string.lower() == string[::-1].lower():
    print(f"{string} is a paliondrome")
    return True
  print(f"{string} is not a paliondrome")
  return False

In [80]:
check_paliondrome("Hannah")

Hannah is a paliondrome


True